name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk unzip
          pip install buildozer

      - name: Compilar APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-apk
          path: bin/*.apk
