name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libgdbm-dev libncurses5-dev libssl-dev libffi-dev readline-common libreadline-dev libdb5.3-dev libgdbm-compat-dev libexpat1-dev liblzma-dev libffi-dev tar
          sudo apt install -y openjdk-17-jdk curl unzip zip
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # --- NOVO: Configuração de Cache ---
      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            .buildozer
            ~/.gradle
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-
      # ----------------------------------

      - name: Compilar APK
        run: |
          # O 'yes' aceita as licenças do Android automaticamente
          yes | buildozer android debug || tail -n 500 buildozer.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
